### ISSUE TITLE
Exception during local host request

### ISSUE THREAD

**Issue by amatthi** [Net-ng/kansha#281]
Hi,

I've followed the most recent developer instructions, but when I try to connect to port 8080 on my local host, I get the following error: 

--------------------------------------------------------------------------------------------------------------------------------

Exception happened during processing of request from ('127.0.0.1', 58752)
Traceback (most recent call last):
  File "/home/agmatthi/mazi/lib/python2.7/site-packages/Paste-2.0.3-py2.7.egg/paste/httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/home/agmatthi/stackless/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/agmatthi/stackless/lib/python2.7/SocketServer.py", line 651, in __init__
    self.handle()
  File "/home/agmatthi/mazi/lib/python2.7/site-packages/Paste-2.0.3-py2.7.egg/paste/httpserver.py", line 459, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/home/agmatthi/stackless/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/agmatthi/mazi/lib/python2.7/site-packages/Paste-2.0.3-py2.7.egg/paste/httpserver.py", line 454, in handle_one_request
    self.wsgi_execute()
  File "/home/agmatthi/mazi/lib/python2.7/site-packages/Paste-2.0.3-py2.7.egg/paste/httpserver.py", line 304, in wsgi_execute
    self.wsgi_start_response)
  File "/home/agmatthi/mazi/lib/python2.7/site-packages/Paste-2.0.3-py2.7.egg/paste/urlmap.py", line 216, in __call__
    return app(environ, start_response)
  File "/home/agmatthi/kansha/kansha/app/comp.py", line 304, in __call__
    return super(WSGIApp, self).__call__(environ, start_response)
  File "/home/agmatthi/mazi/lib/python2.7/site-packages/nagare-0.4.1.post473-py2.7.egg/nagare/wsgi.py", line 411, in __call__
    response = self.create_response(request, 'text/html' if self.always_html else str(request.accept))
  File "/home/agmatthi/mazi/lib/python2.7/site-packages/nagare-0.4.1.post473-py2.7.egg/nagare/wsgi.py", line 299, in create_response
    return self.response_factory(accept)
  File "/home/agmatthi/mazi/lib/python2.7/site-packages/nagare-0.4.1.post473-py2.7.egg/nagare/wsgi.py", line 40, in __init__
    accept = acceptparse.Accept(accept)
TypeError: object() takes no parameters

-----------------------------------------------------------------------------------------------------------------------------

I'm using Ubuntu 16.04. After I load the kansha.local.cfg file, it says that it's listening on 8080, but as soon as I go to the URL, this error occurs. My local.cfg is an exact replica of kansha.cfg since I'm using the built in database, etc. Any idea on what http error could be happening? Thank you in advance!

Best,

Austin

**Comment by nagareproject** [comment]
Hi,

The `Accept()` API of `WebOb` version 1.8 is incompatible with the previous versions. This is fixed in [Nagare 0.5.1](https://github.com/nagareproject/core/commit/3d51c6081e91adcdbff2260fc14002e1cb74a2c4).

As a quick fix, you can add the line `'WebOb<1.8'` in the `install_requires` section of Kansha [setup.py](https://github.com/Net-ng/kansha/blob/master/setup.py#L38) and then re-install it

**Comment by amatthi** [comment]
Thanks!
